
spring:
  application:
    name: music-service
  flyway:
    locations: classpath:/db/migration
    schemas: music
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    root: INFO
    org.springframework.data.jpa.repository: INFO