
spring:
  application:
    name: music-service
  logging:
    level:
      root: INFO
      org.springframework.web: INFO
  flyway:
    locations: classpath:/db/migration
    schemas: ${FLYWAY_SCHEMAS:pomodoro}
    url: ${FLYWAY_URL:jdbc:postgresql://db:5432/music}
    user: ${FLYWAY_USER:flyway_user}
    password: ${FLYWAY_PASSWORD:flyway}
    baselineOnMigrate: true
    enabled: true
    create-schemas: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://db:5432/music?currentSchema=pomodoro}
    username: ${DATASOURCE_USERNAME:my_app_user}
    password: ${DATASOURCE_PASSWORD:nicebreeze}
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true