
spring:
  application:
    name: music-service
  config:
    activate:
      on-profile: dev
  logging:
    level:
      root: DEBUG
      org.springframework.web: INFO
  flyway:
    schemas: music
  datasource:
    url: jdbc:postgresql://db:5432/pomodoro?currentSchema=music
    username: my_app_user
    password: nicebreeze
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: music


logging:
  level:
    root: INFO